=== ratheeshgh/VE/TCMB/Solutions/RetailMobile/WEB-INF/config/Locations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="locations">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="location" maxOccurs="unbounded" minOccurs="1">
     <xs:complexType>
      <xs:sequence>
       <xs:element type="xs:string" name="name" />
       <xs:element type="xs:string" name="type" />
       <xs:element type="xs:float" name="latitude" />
       <xs:element type="xs:float" name="Longitude" />
       <xs:element type="xs:string" name="Address" />
       <xs:element type="xs:string" name="Area" />
       <xs:element type="xs:string" name="City" />
       <xs:element type="xs:string" name="District" />
       <xs:element type="xs:string" name="State" />
       <xs:element type="xs:string" name="Country" />
       <xs:element type="xs:string" name="PostalCode" />
       <xs:element type="xs:string" name="Language" />
       <xs:element type="xs:string" name="Message" />
       <xs:element type="xs:float" name="Phone" />
       <xs:element type="xs:string" name="Email" />
       <xs:element name="facility" maxOccurs="100" minOccurs="0">
        <xs:complexType>
         <xs:sequence>
          <xs:element type="xs:string" name="name" />
          <xs:element type="xs:string" name="description" />
         </xs:sequence>
        </xs:complexType>
       </xs:element>
       <xs:element name="schedule" maxOccurs="7" minOccurs="7">
        <xs:complexType>
         <xs:sequence>
          <xs:element type="xs:string" name="dayofweek" />
          <xs:element type="xs:string" name="closed" />
          <xs:element type="xs:time" name="starttime1" minOccurs="0" />
          <xs:element type="xs:time" name="endtime1" minOccurs="0" />
          <xs:element type="xs:time" name="starttime2" minOccurs="0" />
          <xs:element type="xs:time" name="endtime2" minOccurs="0" />
         </xs:sequence>
        </xs:complexType>
       </xs:element>
      </xs:sequence>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== ratheeshgh/VE/TCMB/Solutions/RetailMobile/WEB-INF/config/Locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Locations.xsd">
 <location>
  <name> Casa Matriz</name>
  <type>Branch</type>
  <latitude>8.977011</latitude>
  <Longitude>-79.522844</Longitude>
  <Address>Marbella, street Aquilino de la Guardia y street 47 Bella Vista</Address>
  <Area>Metro</Area>
  <City>Panama</City>
  <District>Panama</District>
  <State>Panama</State>
  <Country>Panama</Country>
  <PostalCode></PostalCode>
  <Language></Language>
  <Message></Message>
  <Phone>(507)282-2000</Phone>
  <Email>acliente_pa@banesco.com</Email>
   <facility>
   <name>ATM 24 hours</name>
   <description>cash machine</description>
  </facility>
  <schedule>
   <dayofweek>1</dayofweek>
   <closed>N</closed>
   <starttime1>08:00:00</starttime1>
   <endtime1>16:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>2</dayofweek>
   <closed>N</closed>
   <starttime1>08:00:00</starttime1>
   <endtime1>16:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>3</dayofweek>
   <closed>N</closed>
   <starttime1>08:00:00</starttime1>
   <endtime1>16:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>4</dayofweek>
   <closed>N</closed>
   <starttime1>08:00:00</starttime1>
   <endtime1>16:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>5</dayofweek>
   <closed>N</closed>
   <starttime1>08:00:00</starttime1>
   <endtime1>16:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>6</dayofweek>
   <closed>N</closed>
   <starttime1>09:00:00</starttime1>
   <endtime1>13:00:00</endtime1>
  </schedule>
  <schedule>
   <dayofweek>7</dayofweek>
   <closed>Y</closed>
  </schedule>
 </location>
 </locations>
